# Generated by Django 5.0.6 on 2024-06-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_question_order_alter_question_answer_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='duration',
            field=models.PositiveIntegerField(default=300),
        ),
    ]
